### ISSUE TITLE
execinfo is a separate library on alpine

### ISSUE THREAD

**Issue by Infinoid** [genshen/docker-clang-toolchain#6]
Hi,

Quick tip.  Your Dockerfile says (line 71):

```
# NOTE execinfo.h not available on musl -> lldb and compiler-rt:fuzzer/sanitizer/profiler cannot be built!
```

It is available, it's just implemented in a separate library.  `apk install libexecinfo-dev` to get it.

https://pkgs.alpinelinux.org/package/v3.15/main/x86_64/libexecinfo-dev

Hope this helps.

**Comment by genshen** [comment]
👍 Thanks for your information. I will try it as soon as possible.
