### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pettermk** [genshen/docker-clang-toolchain#9]
Hi,

I was using this code in a project at work and it's been very useful for us, so first of all thanks for the effort and sharing the code!

Now for maintaining different LLVM versions, we have forked it, and I just noticed there isn't any license associated with this repo. So I'm wondering if you have intended to share the code for such use cases, and if you have, it would be ever so helpful if you'd attach a license to this work. If you haven't, we will promptly take down the fork and cease using it.

Thanks,
Petter

**Comment by genshen** [comment]
Thanks for your feedback and suggesttion.  When I pushed my first commit to this repo, there is just a simple reason —— I want to share my code and my works to others (People's gratitude and feedback makes me happy!).
So, please feel free to fork it and share it to anyone who feels it is useful.
I will continue to update this repo, and look forward for your feedbacks or PRs if possible.
I will add a License file (maybe a MIT License) to this repo.

**Comment by pettermk** [comment]
That's great! I'm going to look into our changes on Monday and see if it is something we can upstream, or discuss how to resolve. Essentially we had added the flang compiler and added some flexibility regarding the built versions. Thanks again - I'll close the issue for now
